[providers]
php = "82"

[phases.setup]
nixPkgs = ["php82", "php82Packages.pdo_mysql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:${PORT:-8080} -t ."

